[project]
name = "SnakeMD"
description = "A markdown generation library for Python."
version = "2.0.0"
license = "MIT"

authors = [
    {name = "Jeremy Grifski", email = "jeremy.grifski@therenegadecoder.com"}
]

readme = "README.md"
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Topic :: Documentation :: Sphinx",
]

requires-python = ">=3.8"

[project.urls]
homepage = "https://www.snakemd.io"
documentation = "https://www.snakemd.io/en/latest/docs/"
repository = "https://github.com/TheRenegadeCoder/SnakeMD"
changelog = "https://www.snakemd.io/en/latest/version-history/"
