name: Docs

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get latest tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install sphinx_rtd_theme
        pip install sphinx-issues

    - name: Sphinx Build
      run: python setup.py build_sphinx

    - name: Copy HTML
      run: cp -a docsrc/_build/dirhtml/. docs/${{ env.RELEASE_VERSION }}
        
    - name: Update Index
      run: echo "<meta http-equiv=\"refresh\" content=\"0; url=./${{ env.RELEASE_VERSION }}/\" />" > docs/index.html

    - name: Publish Documentation
      continue-on-error: true
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add .
        git commit -m "Update documentation"
        git push origin HEAD:main
