name: Deploy

on:
  pull_request:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get latest tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install sphinx_rtd_theme

    - name: Sphinx Build
      run: python setup.py build_sphinx

    - name: Copy HTML
      run: | 
        echo cp -a docsrc/_build/dirhtml/. docs/${{ env.RELEASE_VERSION }}
        echo "<meta http-equiv=\"refresh\" content=\"0; url=./${{ env.RELEASE_VERSION }}/index.html\" />" > docs/index.html

    - name: Commit Changes
      uses: EndBug/add-and-commit@v5 
      with:
        message: |
          Generated documentation
            
            
          on-behalf-of: @TheRenegadeCoder <jeremy.grifski@therenegadecoder.com>
        author_name: Jeremy Grifski
        author_email: jeremy.grifski@gmail.com

      env:
        # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
